name: Build DataSonifier Executables

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'  # Trigger only when Python files are changed
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller matplotlib numpy pygame

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed sonifier.py

    - name: Rename executable for clarity
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          mv dist/sonifier.exe dist/sonifier-windows.exe
        elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          mv dist/sonifier dist/sonifier-linux
        else
          mv dist/sonifier dist/sonifier-macos
        fi

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: sonifier-${{ matrix.os }}
        path: dist/sonifier-*