name: Build DataSonifier Executables

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller matplotlib numpy pygame

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed sonifier.py

    - name: Rename executable for clarity
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          mv dist/sonifier.exe dist/sonifier-windows.exe
        elif [ "${{ matrix.os }}" == "Ubuntu-latest" ]; then
          mv dist/sonifier dist/sonifier-linux
        else
          mv dist/sonifier dist/sonifier-macos
        fi

    - name: Debug artifact files
      shell: bash
      run: |
        echo "Listing files in dist directory:"
        ls -lh dist/

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: sonifier-${{ matrix.os }}
        path: dist/sonifier-*

    - name: Debug uploaded artifact
      shell: bash
      run: |
        echo "Artifact name: sonifier-${{ matrix.os }}"

  update-readme:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get latest workflow run artifacts
      uses: actions/github-script@v7
      id: get-artifacts
      with:
        script: |
          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
          });
          console.log('All artifacts:', artifacts.data.artifacts);
          const artifactData = {
            windows: 'https://github.com/EatPowerNode/DataSonifier/blob/main',  // Fallback URL
            linux: 'https://github.com/EatPowerNode/DataSonifier/blob/main',
            macos: 'https://github.com/EatPowerNode/DataSonifier/blob/main'
          };
          for (const artifact of artifacts.data.artifacts) {
            const downloadUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts/${artifact.id}`;
            console.log(`Found artifact: ${artifact.name} with URL: ${downloadUrl}`);
            if (artifact.name === 'sonifier-windows-latest') {
              artifactData.windows = downloadUrl;
            } else if (artifact.name === 'sonifier-ubuntu-latest') {
              artifactData.linux = downloadUrl;
            } else if (artifact.name === 'sonifier-macos-latest') {
              artifactData.macos = downloadUrl;
            }
          }
          console.log('Final artifact URLs:', artifactData);
          return artifactData;

    - name: Debug artifact URLs
      run: |
        echo "Raw output: ${{ steps.get-artifacts.outputs.result }}"
        echo "Windows URL: $(echo '${{ steps.get-artifacts.outputs.result }}' | jq -r '.windows')"
        echo "Linux URL: $(echo '${{ steps.get-artifacts.outputs.result }}' | jq -r '.linux')"
        echo "macOS URL: $(echo '${{ steps.get-artifacts.outputs.result }}' | jq -r '.macos')"

    - name: Update README with artifact URLs
      run: |
        WINDOWS_URL=$(echo '${{ steps.get-artifacts.outputs.result }}' | jq -r '.windows')
        LINUX_URL=$(echo '${{ steps.get-artifacts.outputs.result }}' | jq -r '.linux')
        MACOS_URL=$(echo '${{ steps.get-artifacts.outputs.result }}' | jq -r '.macos')
        if [ -z "$WINDOWS_URL" ] || [ -z "$LINUX_URL" ] || [ -z "$MACOS_URL" ]; then
          echo "Error: One or more artifact URLs are empty. Exiting."
          exit 1
        fi
        sed -i "s|- \[Windows (64-bit)\](.*)|- [Windows (64-bit)]($WINDOWS_URL)|" README.md
        sed -i "s|- \[Linux (64-bit)\](.*)|- [Linux (64-bit)]($LINUX_URL)|" README.md
        sed -i "s|- \[macOS (64-bit)\](.*)|- [macOS (64-bit)]($MACOS_URL)|" README.md

    - name: Debug README content
      run: |
        cat README.md

    - name: Commit and push updated README
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add README.md
        git commit -m "Update README with latest artifact URLs"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}